schema_version: 1

context:
  version: "3.13.1"

package:
  name: goimports-reviser
  version: ${{ version }}

source:
  url: https://github.com/incu6us/goimports-reviser/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 736e3d92af9cebf273a287ba5e02c06092db62de53eaef738b3de88de43ce41c

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - goimports-reviser --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Right imports sorting & code formatting tool (goimports alternative)
  homepage: https://github.com/incu6us/goimports-reviser
  repository: https://github.com/incu6us/goimports-reviser

extra:
  recipe-maintainers:
    - danielnachun
