schema_version: 1

context:
  version: "3.12.5"

package:
  name: goimports-reviser
  version: ${{ version }}

source:
  url: https://github.com/incu6us/goimports-reviser/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 90b97c2ae009e858e665bf26c5b20da0a360d1b3f7066549ed26a42fbde1c1db

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - goimports-reviser --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Right imports sorting & code formatting tool (goimports alternative)
  homepage: https://github.com/incu6us/goimports-reviser
  repository: https://github.com/incu6us/goimports-reviser

extra:
  recipe-maintainers:
    - danielnachun
