schema_version: 1

context:
  version: "3.13.0"

package:
  name: goimports-reviser
  version: ${{ version }}

source:
  url: https://github.com/incu6us/goimports-reviser/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 2af9b83f9457e2111100b2d2cb48ac5abfc20132e662424baa5958a90d7c45a9

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - goimports-reviser --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Right imports sorting & code formatting tool (goimports alternative)
  homepage: https://github.com/incu6us/goimports-reviser
  repository: https://github.com/incu6us/goimports-reviser

extra:
  recipe-maintainers:
    - danielnachun
